name: Build and Release

on:
  push:
    branches:
      - main # Or your default branch
    tags:
      - 'v*' # Trigger on version tags like v0.1.1

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      
      - name: Prepare artifact
        run: |
          mkdir -p release
          cp target/x86_64-unknown-linux-gnu/release/sigil-gen release/sigil-gen-linux
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: sigil-gen-linux
          path: release/sigil-gen-linux

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu
      
      - name: Add Windows target
        run: rustup target add x86_64-pc-windows-gnu
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu
      
      - name: Prepare artifact
        run: |
          mkdir -p release
          cp target/x86_64-pc-windows-gnu/release/sigil-gen.exe release/sigil-gen-windows.exe
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: sigil-gen-windows
          path: release/sigil-gen-windows.exe

  create-release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') # Only run for version tags
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/ # Download all artifacts to this directory

      - name: List downloaded artifacts (for debugging)
        run: ls -R artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          # token: ${{ secrets.GITHUB_TOKEN }} # This line is optional, token is default
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: |
            artifacts/sigil-gen-linux/sigil-gen-linux
            artifacts/sigil-gen-windows/sigil-gen-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
