name: Build and Release

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      
      - name: Prepare artifact
        run: |
          mkdir -p release
          cp target/x86_64-unknown-linux-gnu/release/sigil-gen release/sigil-gen-linux
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: sigil-gen-linux
          path: release/sigil-gen-linux

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu
      
      - name: Add Windows target
        run: rustup target add x86_64-pc-windows-gnu
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu
      
      - name: Prepare artifact
        run: |
          mkdir -p release
          cp target/x86_64-pc-windows-gnu/release/sigil-gen.exe release/sigil-gen-windows.exe
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: sigil-gen-windows
          path: release/sigil-gen-windows.exe
